import { ref } from "vue";

export const mainCategory = ref(["지체 장애 및 고령자", "시각 장애", "청각 장애", "영유아 가족"]);
export const subCategory = ref({
  "지체 장애 및 고령자": [
    "🚗 주차 여부",
    "🚌 대중교통",
    "👌 접근로",
    "🎫 매표소",
    "📢 홍보물",
    "♿ 휠체어",
    "🏃 출입 통로",
    "🔼 엘리베이터",
    "화장실",
    "🏟️ 관람석",
    "🛏️ 객실",
    "🦽 지체장애 기타",
  ],
  "시각 장애": [
    "🦯 점자 블록",
    "🐕‍🦺 보조견 동반",
    "‍‍💁‍ 안내 요원",
    "🎧 오디오 가이드",
    "🔠 큰 활자 홍보물",
    "📃 점자 홍보물 및 점자 표지판",
    "🛠️ 유도안내설비",
    "👨🏻‍🦯 시각장애 기타",
  ],
  "청각 장애": [
    "🧏 수화 안내",
    "📼 영상 자막 안내",
    "🛏️ 청각장애인용 객실",
    "🧏‍♂️ 청각 장애 기타 상세",
  ],
  "영유아 가족": ["👶🏻 유모차", "🚼 수유실", "🪑 유아용 보조 의자", "👪 영유아 가족 기타"],
});

export const barrierFreeInfo = {
  audioguide: "🎧 오디오 가이드",
  auditorium: "🎟️ 관람석",
  babysparechair: "🪑 유아용 보조 의자",
  bigprint: "🔠 큰 활자 홍보물",
  blindhandicapetc: "👨🏻‍🦯 시각장애 기타",
  braileblock: "🦯 점자 블록",
  brailepromotion: "📃 점자 홍보물 및 점자 표지판",
  elevator: "🔼 엘리베이터",
  restroom: "🚻 화장실",
  room: "🛏️ 객실",
  handicapetc: "♿ 휠체어",
  helpdog: "🐕‍🦺 보조견 동반",
  guidehuman: "‍‍💁‍ 안내 요원",
  guidesystem: "🛠️ 유도안내설비",
  signguide: "🧏 수화 안내",
  videoguide: "📼 영상 자막 안내",
  hearingroom: "🛏️ 청각장애인용 객실",
  hearinghandicapetc: "🧏‍♂️ 청각 장애 기타 상세",
  stroller: "👶🏻 유모차",
  lactationroom: "🚼 수유실",
  infantsfamilyetcs: "👪 영유아 가족 기타",
  parking: "🚗 주차 여부",
  route: "👌 접근로",
  publictransport: "🚌 대중교통",
  ticketoffice: "🎫 매표소",
  promotion: "📢 홍보물",
  wheelchair: "🦽 지체장애 기타",
  exit: "🏃 출입 통로",
};

export const barrierFreeEmoji = {
  audioguide: "🎧",
  auditorium: "🎟️",
  babysparechair: "🪑",
  bigprint: "🔠",
  blindhandicapetc: "👨🏻‍🦯",
  braileblock: "🦯",
  brailepromotion: "📄",
  elevator: "🔼",
  restroom: "🚻",
  room: "🛏️",
  handicapetc: "♿",
  helpdog: "🐕",
  guidehuman: "💁",
  guidesystem: "🗺️",
  signguide: "🧏‍♂️",
  videoguide: "📽️",
  hearingroom: "🛏️",
  hearinghandicapetc: "🦻",
  stroller: "👶",
  lactationroom: "🚼",
  infantsfamilyetcs: "👪",
  parking: "🅿️",
  route: "🚌",
  publictransport: "🚶",
  ticketoffice: "🎫",
  promotion: "📢",
  wheelchair: "🦽",
  exit: "🚪",
};
